// ScooterEdu MN — Seed өгөгдөл (багц, хамтрагч, жолооны курс, дадлагын элемент)
// Сургалтын контент ба асуултын сан → prisma/curriculum.ts

export {
  CONTENT_VERSION,
  modules,
  questions,
} from './curriculum';
export type { SeedOption, SeedQuestion, SeedModule } from './curriculum';

// ── ҮНИЙН БАГЦУУД ────────────────────────────────────────────────
export const packages = [
  {
    code: 'BASIC',
    name: 'Үндсэн',
    price: 19900,
    priceLabel: '',
    tier: 'BASIC',
    includesPractice: false,
    practiceSessions: 0,
    includesCard: false,
    enrollable: true,
    badge: '',
    description: 'Онлайн хичээл, шалгалт болон дижитал гэрчилгээ. Хурдан эхлэлт.',
    features: [
      '6 модуль онлайн хичээл',
      'Онлайн шалгалт (30 асуулт)',
      'Дижитал гэрчилгээ + QR',
      'Нийтийн баталгаажуулалт',
    ],
    sortOrder: 1,
  },
  {
    code: 'STANDARD',
    name: 'Стандарт',
    price: 29900,
    priceLabel: '',
    tier: 'STANDARD',
    includesPractice: true,
    practiceSessions: 1,
    includesCard: false,
    enrollable: true,
    badge: 'Эрэлттэй',
    description: 'Онлайн сургалт дээр практик дадлага нэмэгдсэн бүрэн багц.',
    features: [
      'Үндсэн багцын бүх боломж',
      '1 удаагийн практик дадлага',
      'Жолооны курст QR баталгаажуулалт',
      'Бүрэн баталгаажсан гэрчилгээ',
    ],
    sortOrder: 2,
  },
  {
    code: 'PRO',
    name: 'Pro',
    price: 49900,
    priceLabel: '',
    tier: 'PRO',
    includesPractice: true,
    practiceSessions: 2,
    includesCard: true,
    enrollable: true,
    badge: 'Шинэ',
    description: 'Хамгийн дэлгэрэнгүй багц — нэмэлт дадлага ба биет карт.',
    features: [
      'Стандарт багцын бүх боломж',
      '2 удаагийн практик дадлага',
      'Биет гэрчилгээний карт',
      'Тэргүүлэх дэмжлэг',
    ],
    sortOrder: 3,
  },
  {
    code: 'B2B',
    name: 'Байгууллага (B2B)',
    price: 25000,
    priceLabel: '25,000₮/хүн',
    tier: 'B2B',
    includesPractice: true,
    practiceSessions: 1,
    includesCard: false,
    enrollable: false,
    badge: 'Шинэ',
    description: '10+ ажилтантай байгууллагад зориулсан багц бүртгэл, хяналт.',
    features: [
      '10+ ажилтны багц бүртгэл',
      'Стандарт багцын бүх боломж',
      'Байгууллагын тайлан, хяналт',
      'Гэрээт төлбөр',
    ],
    sortOrder: 4,
  },
  {
    code: 'API',
    name: 'API жилийн лиценз',
    price: 0,
    priceLabel: 'Жилийн лиценз',
    tier: 'API',
    includesPractice: false,
    practiceSessions: 0,
    includesCard: false,
    enrollable: false,
    badge: '',
    description: 'Скүүтэр түрээс болон бусад аппликейшн холбогдох API лиценз.',
    features: [
      'Сертификат шалгах API',
      'Урамшуулал олгох API',
      'Хэрэглэгч холболтын API',
      'Түрээсийн апп интеграц',
    ],
    sortOrder: 5,
  },
];

// ── ХАМТРАГЧ КОМПАНИУД (Судалгааны 1.5) ──────────────────────────
export const partners = [
  {
    name: 'Jet Sharing Mongolia',
    code: 'JET',
    appName: 'JET App',
    rewardPoints: 1000,
    discountPercent: 10,
    logoColor: '#FF5A1F',
    scooterCount: '~6,000 скүүтэр',
    description: 'Монголын хамгийн том скүүтэр түрээсийн платформ. Сургалт төгсөгчдөд 1,000 оноо + 30 минут үнэгүй.',
  },
  {
    name: 'Tabo (VMC Group)',
    code: 'TABO',
    appName: 'Tabo / Tapa Trip',
    rewardPoints: 500,
    discountPercent: 15,
    logoColor: '#16A34A',
    scooterCount: '~1,500 скүүтэр',
    description: 'VMC группын скүүтэр түрээс. 500 оноо + 15% хөнгөлөлт.',
  },
  {
    name: 'Eco Bike',
    code: 'ECOBIKE',
    appName: 'Eco Bike App',
    rewardPoints: 500,
    discountPercent: 0,
    logoColor: '#0EA5E9',
    scooterCount: '~2,500 цахилгаан дугуй',
    description: 'Цахилгаан дугуй түрээсийн үйлчилгээ. Сургалт төгсөгчдөд 500 оноо.',
  },
  {
    name: 'GoGo Scooter',
    code: 'GOGO',
    appName: 'GoGo App',
    rewardPoints: 500,
    discountPercent: 10,
    logoColor: '#9333EA',
    scooterCount: 'Тодорхойлогдсон',
    description: 'Хотын скүүтэр түрээс. Урамшуулал тохиролцлоор.',
  },
  {
    name: 'Flash',
    code: 'FLASH',
    appName: 'Flash App',
    rewardPoints: 500,
    discountPercent: 10,
    logoColor: '#EAB308',
    scooterCount: 'Тодорхойлогдсон',
    description: 'Шуурхай скүүтэр түрээс. Урамшуулал тохиролцлоор.',
  },
  {
    name: 'ScootMN',
    code: 'SCOOTMN',
    appName: 'ScootMN',
    rewardPoints: 500,
    discountPercent: 10,
    logoColor: '#EC4899',
    scooterCount: 'Тодорхойлогдсон',
    description: 'Дотоодын скүүтэр түрээсийн үйлчилгээ.',
  },
  {
    name: 'Bird.mn',
    code: 'BIRD',
    appName: 'Bird Platform',
    rewardPoints: 500,
    discountPercent: 10,
    logoColor: '#1B448A',
    scooterCount: 'Тодорхойлогдсон',
    description: 'Олон улсын Bird платформын Монгол дахь үйлчилгээ.',
  },
];

// ── ГЭРЭЭТ ЖОЛООНЫ КУРС (дадлагын талбай) ────────────────────────
export const drivingSchools = [
  {
    name: 'УБ Драйв Жолооны Сургууль',
    address: 'Сүхбаатар дүүрэг, 1-р хороо, Энхтайваны өргөн чөлөө 25',
    district: 'Сүхбаатар',
    lat: 47.918,
    lng: 106.917,
    phone: '7011-2233',
    contractNumber: 'DS-2026-001',
    capacityPerDay: 30,
  },
  {
    name: 'Сэлбэ Дадлагын Талбай',
    address: 'Баянгол дүүрэг, 5-р хороо, Дунд гол гудамж 14',
    district: 'Баянгол',
    lat: 47.905,
    lng: 106.86,
    phone: '7022-4455',
    contractNumber: 'DS-2026-002',
    capacityPerDay: 20,
  },
  {
    name: 'Хан-Уул Скүүтэр Дадлага',
    address: 'Хан-Уул дүүрэг, 15-р хороо, Чингисийн өргөн чөлөө 8',
    district: 'Хан-Уул',
    lat: 47.886,
    lng: 106.91,
    phone: '7033-6677',
    contractNumber: 'DS-2026-003',
    capacityPerDay: 25,
  },
];

// ── ПРАКТИК ДАДЛАГЫН ЭЛЕМЕНТҮҮД (Судалгааны 9.1) ─────────────────
export const practiceElements = [
  { code: 'A', titleMn: 'Эхлэх, зогсох', criteria: 'Жигд эхлэх, аюулгүй зогсох', durationMin: 20 },
  { code: 'B', titleMn: 'Шулуун явах', criteria: 'Нарийн шугам дагах', durationMin: 20 },
  { code: 'C', titleMn: 'Эргэлт (баруун/зүүн/U)', criteria: 'Зөв эргэлт', durationMin: 30 },
  { code: 'D', titleMn: 'Саад давах (шон тойрох)', criteria: 'Нарийн замаар нэвтрэх', durationMin: 30 },
  { code: 'E', titleMn: 'Гар хурдаар явах', criteria: 'Тэнцвэр хадгалах', durationMin: 20 },
  { code: 'F', titleMn: 'Яаралтай зогсолт', criteria: '7 метрт зогсох', durationMin: 20 },
  { code: 'G', titleMn: 'Замын хөдөлгөөнд нэгдэх', criteria: 'Зөв ажиглалт, эргэлт', durationMin: 30 },
];
